id: PA90A52F9
initial_creation_type: ocr
source_metadata:
  volumes:
    2c610ab81fb5469bbf349c1835112d59:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: གནས་ཆེན་པོ་བརྒྱད་ཀྱི་མཆོད་རྟེན་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
